### ISSUE TITLE
Use env to store private keys, mnemonic and keystore in tests folder

### ISSUE THREAD

**Issue by EnoRage** [bnb-chain/javascript-sdk#136]
Here you can see mnemonic:
https://github.com/binance-chain/javascript-sdk/blob/master/__tests__/client.test.js#L7

I found some money on this mnemonic on mainnet too. Is it there for specific purpose?)

**Comment by notatestuser** [comment]
Ha, funny to see that it has some funds on the mainnet.. not sure how that happened. However, we use this mnemonic for some end-to-end tests.

Thanks for pointing this out - it should really be stored in an environment variable or something.
