### ISSUE TITLE
Multisig account support

### ISSUE THREAD

**Issue by amitsharma8891** [bnb-chain/javascript-sdk#188]
Does it support multisig account? If yes how to proceed?

**Comment by huangsuyu** [comment]
Hello, @amitsharma8891 

This feature will come soon, please stay tuned!

**Comment by xiaoxuez** [comment]
cosmos-sdk support multisig account. can i use it?

**Comment by huangsuyu** [comment]
> cosmos-sdk supports multisig account. can i use it?

Hello, 

At the moment, Multisig is not supported yet and the recommended way to secure your keys is through Threshold Signature Scheme(TSS). Please take a look at the implementation here: https://github.com/binance-chain/tss-lib

**Comment by xiaoxuez** [comment]
> > cosmos-sdk supports multisig account. can i use it?
> 
> Hello,
> 
> At the moment, Multisig is not supported yet and the recommended way to secure your keys is through Threshold Signature Scheme(TSS). Please take a look at the implementation here: https://github.com/binance-chain/tss-lib

thanks.
When i read [doc](https://docs.binance.org/tss.html#where-can-i-download-the-binance-tss-cli),
I have some doubt. It supports mainnet cli, but the next line in doc is
> Warning: Please note that TSS is still an experimental function and please do not test this on mainnet.

So is tss finished?  or just an experimental function

**Comment by xiaoxuez** [comment]
> > > cosmos-sdk supports multisig account. can i use it?
> > 
> > 
> > Hello,
> > At the moment, Multisig is not supported yet and the recommended way to secure your keys is through Threshold Signature Scheme(TSS). Please take a look at the implementation here: https://github.com/binance-chain/tss-lib
> 
> thanks.
> When i read [doc](https://docs.binance.org/tss.html#where-can-i-download-the-binance-tss-cli),
> I have some doubt. It supports mainnet cli, but the next line in doc is
> 
> > Warning: Please note that TSS is still an experimental function and please do not test this on mainnet.
> 
> So is tss finished? or just an experimental function


I find my answer.  Thanks.
