### ISSUE TITLE
Add missing decoder types: transfer, cancel order, ...

### ISSUE THREAD

**Issue by notatestuser** [bnb-chain/javascript-sdk#211]
https://github.com/binance-chain/javascript-sdk/blob/a089e04aa3299ebb9719e44380a1cd694a7829c4/src/decoder/types.js#L1

The type choices in this file are very random and this should be improved.

**Comment by xzjcool** [comment]
We only add rpc related types before

**Comment by notatestuser** [comment]
You can get these over RPC (tx, tx_search, ...)

**Comment by xzjcool** [comment]
So it's time to add all the stuffs

**Comment by naiemk** [comment]
+1 on this. We had to write our own. Would much rather use the officially supported one:

https://github.com/ferrumnet/bnb-tx-decoder
