### ISSUE TITLE
Remove the need for libusd/libudev when installing with --no-optional

### ISSUE THREAD

**Issue by stefanionescu** [bnb-chain/javascript-sdk#214]
I shouldn't need to install libudev-dev, libusb-dev and usbutils when I don't want Ledger support.

For now I had to fork this repo and eliminate all Ledger-related code so I don't get a "libusd not found" error when I npm install.

It would be nice to make an option where if I install with --no-option I don't need to also install the above mentioned deps.

**Comment by notatestuser** [comment]
You can use `--no-optional`.
```bash
$ npm i @binance-chain/javascript-sdk --no-optional
```
From the readme: https://github.com/binance-chain/javascript-sdk#install-the-npm-package

**Comment by notatestuser** [comment]
Closed by mistake. Let me know if there's something I'm missing here.

**Comment by stefanionescu** [comment]
I did use --no-optional and it still gave me an error saying something like "libudev not found"

**Comment by suraneti** [comment]
@stefanionescu can you try with `yarn add @binance-chain/javascript-sdk --no-optional`.

**Comment by stefanionescu** [comment]
I tried --no-optional and it still gives the same errors. For now I forked the repo and removed libusd/libudev entirely from the code
