### ISSUE TITLE
getTransactions doesn't work

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [bnb-chain/javascript-sdk#304]
I'm running `client.getTransactions("tbnb1uxgesw2ktt524t29zytdjjm3kv3mkuczzmjz4x")` but all I get is : `{ result: { tx: [], total: 0 }, status: 200 }` if you check [explorer](https://testnet-explorer.binance.org/address/tbnb1uxgesw2ktt524t29zytdjjm3kv3mkuczzmjz4x) you will see that this account has multiple transaction but non is returned by `client.getTransactions`

**Comment by mutobui** [comment]
Please check the API  you connected with

**Comment by Mahsa-Bastankhah** [comment]
I'm connecting to : https://testnet-dex.binance.org/

**Comment by Gui-greg** [comment]
It is only returns transactions in the previous 24h. Please try again to validate and if that is true put a comment to my issue to try to fix it: https://github.com/binance-chain/javascript-sdk/issues/314
