### ISSUE TITLE
Please update dependency axios to to version 0.21.1 or later

### ISSUE THREAD

**Issue by pw96pw96pw96** [bnb-chain/javascript-sdk#312]
Axios security alert:
https://github.com/advisories/GHSA-4w2v-q235-vp99

**Comment by siibars** [comment]
hi @notatestuser 
Would it be possible to move forward with this pull request? https://github.com/binance-chain/javascript-sdk/pull/310/files
to update to 0.21.0, as it as been reported above is an axios vulnerability.
Cheers

**Comment by pw96pw96pw96** [comment]
Sure.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
From: Simon ***@***.***>
Date: 6/28/21 9:44 AM (GMT-08:00)
To: binance-chain/javascript-sdk ***@***.***>
Cc: Peng Wang ***@***.***>, Author ***@***.***>
Subject: Re: [binance-chain/javascript-sdk] Please update dependency axios to to version 0.21.1 or later (#312)


hi @notatestuser<https://github.com/notatestuser>
Would it be possible to move forward with this pull request? https://github.com/binance-chain/javascript-sdk/pull/310/files
to update to 0.21.0, as it as been reported above is an axios vulnerability.
Cheers
