### ISSUE TITLE
How to get status of a transaction and number of confirmations for a transaction

### ISSUE THREAD

**Issue by amitOodles** [bnb-chain/javascript-sdk#325]
Following the api examples given 
[here](https://github.com/binance-chain/javascript-sdk/blob/master/docs/examples.md)

In the wallet transfer example, i get the response object with status and result field, so getting the status value as 200 means that my transaction has been broadcasted successfully on the network. 

a) Once the broadcast is successful, how can i know the status of my transaction i.e. if it has been mined or is it still pending and was it successfully mined or not. (In web3.js i can check through the transactionReceipt api which returns a receipt object with a status field). 

b) How can i know the number of confirmations for my transaction ? And how many confirmations should i wait for to consider the transaction as successful. Also i am unable to find an api to get the current block height in the docs.

**Comment by Anon79** [comment]
ฉันยังงงไม่เข้าใจในการับสินทรัพย์เก็บเข้ากระเป๋า
