### ISSUE TITLE
> Have a second worksheet in each spreadsheet file that contains some options for the generated page...

### ISSUE THREAD

**Issue by Bibianoo** [bnb-chain/javascript-sdk#341]
> Have a second worksheet in each spreadsheet file that contains some options for the generated page...

_Originalmente postado por @mahmud1989 em https://github.com/jlord/sheetsee.js/issues/26#issuecomment-873626019_

**Comment by Bibianoo** [comment]
🚀🚀🚀

**Comment by Lippertt** [comment]
> > Have a second worksheet in each spreadsheet file that contains some options for the generated page...
> 
> 
> 
> _Originalmente postado por @mahmud1989 em https://github.com/jlord/sheetsee.js/issues/26#issuecomment-873626019_

[![Unit Test](https://github.com/bnb-chain/bsc/actions/workflows/unit-test.yml/badge.svg)](https://github.com/bnb-chain/bsc/actions/workflows/unit-test.yml)
