### ISSUE TITLE
api error recently

### ISSUE THREAD

**Issue by lijianl** [bnb-chain/javascript-sdk#369]
Hi, js sdk is unavailable recently, could you guys check why

```js
const bnbApi = require('@binance-chain/javascript-sdk')
let baseUrl = 'https://dex.binance.org/';
const client = new bnbApi.BncClient(baseUrl);
client.chooseNetwork('mainnet');

async function bnb_account(addr) {
    let address = addr || n1_addr;
    return client.getAccount(address).then(console.log).catch(console.log);
}
bnb_account();
```

**Comment by bin-dogami** [comment]
I have the same question. Why can't these guys get things right!!!
@lijianl Do you find the other way to get the balance and transfer?

**Comment by Nazarenko1** [comment]
> Привіт, js sdk нещодавно недоступний. Дізнайтеся чому
> 
> ```js
> const bnbApi = require('@binance-chain/javascript-sdk')
> let baseUrl = 'https://dex.binance.org/';
> const client = new bnbApi.BncClient(baseUrl);
> client.chooseNetwork('mainnet');
> 
> async function bnb_account(addr) {
>     let address = addr || n1_addr;
>     return client.getAccount(address).then(console.log).catch(console.log);
> }
> bnb_account();
> ```
const bnbApi = require('@binance-chain/javascript-sdk')
let baseUrl = 'https://dex.binance.org/';
const client = new bnbApi.BncClient(baseUrl);
client.chooseNetwork('mainnet');

async function bnb_account(addr) {
    let address = addr || n1_addr;
    return client.getAccount(address).then(console.log).catch(console.log);
}
bnb_account();
