### ISSUE TITLE
client should be split into two pieces

### ISSUE THREAD

**Issue by notatestuser** [bnb-chain/javascript-sdk#57]
Right now client has methods that rely on `this.privateKey` and others that take parameters in arguments (such as `checkAddress(address)`). These separate concerns should be separated out into two classes.

**Comment by Johnsavadkuhi** [comment]
class Signer { }   class BncClient {}   , remove setPrivateKey in BncClient

**Comment by notatestuser** [comment]
@Johnsavadkuhi putting it in a separate class is essentially the same thing in JS.
