### ISSUE TITLE
Use a separate class for Account (keys, address)

### ISSUE THREAD

**Issue by Johnsavadkuhi** [bnb-chain/javascript-sdk#82]
client/index.js should be only for interacting with binance chain like send token , issue token and so

**Comment by notatestuser** [comment]
If I am interpreting this correctly, I agree - it would be nice to have a separate `Account` (or similar) class to hold the address and private key.

**Comment by notatestuser** [comment]
How do you feel about the structure proposed in #43?

**Comment by Johnsavadkuhi** [comment]
@notatestuser  yes #43 is good structure but i have a question , why getBalance() and  getAccount () in  Account Class  ?  i recommend delete getBalance and getAccount and then put them in client/index

**Comment by Johnsavadkuhi** [comment]
@notatestuser 

![Screenshot (27)](https://user-images.githubusercontent.com/6722877/54880605-fd4e3280-4e63-11e9-8ac9-60fc8e8671d4.png)
